# Generated by Django 4.2.4 on 2023-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('work_phone', models.CharField(max_length=20)),
                ('personal_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
